### ISSUE TITLE
options.document should be obsoleted

### ISSUE THREAD

**Issue by shogun70** [glennjones/microformat-shiv#17]
This is partly because `options.document` can always be inferred from `options.node` - it is either `options.node.ownerDocument` or `document`.

More problematic is that currently you can specify an `options.node` that is not within `options.document`. `getItems()` won't report an error; on the contrary it will parse microformats within `options.node`, but do a clean-up within `options.document`. This leaves the tree under `options.node` with `@rootids` which prevents `getItems()` parsing correctly if it is called again on the same `options.node`.

**Comment by glennjones** [comment]
Hi Sean,  Sorry its taken a year to answer this point. Yes the `options.document` issue you rightly pointed out was a result of me using the same code in node.js with a cut down DOM which did not support `node.ownerDocument`. Your right I should of added some defensive error in microformat-shiv. 

I have now just rewritten the microformat-shiv and `options.document` is no more.
