### ISSUE TITLE
Parsing tantek.com with h-card filter takes almost 4 minutes

### ISSUE THREAD

**Issue by mkaply** [glennjones/microformat-shiv#24]
I am using this code:

var mfs = Microformats.get({filters: ["h-card"], node: doc, document: doc});

to get the microformats on tantek.com (I'm in an extension). It hangs the browser for almost four minutes. The looping seems to be happening in findFilterNodes.

If I change it to:

var mfs = Microformats.get({node: doc, document: doc});

it comes back immediately with an hcard in mfs.items.

I'm looked through the findFilterNodes code and nothing is jumping out at me...

**Comment by mkaply** [comment]
I did some debugging on this and no one call is jumping out as being expensive. It's just that the entire process is expensive.

Can the v1 mapping be moved out of the loop so it doesn't get done every time?

**Comment by mkaply** [comment]
The v1 mapping is the problem:

https://github.com/glennjones/microformat-shiv/blob/master/microformat-shiv.js#L413

This code is getting executed on every loop and it keeps adding vcard over and over to the list.

So we end up with tons of repeat filters.

**Comment by glennjones** [comment]
Hi Mike sorry to hear your having performance issue. 

The last time I looked at tantek.com home page it was taken about 200ms on desktop and about 1000ms on mobile browsers. So not as fast as I would like, but not the sort of figures you are getting. I am just about to go out for the evening, but I will have a look at it first thing in the morning. 

Most people don't bother with the filter so there maybe a bug which has been hidden for a while.I will have a look at the line you pointed out

**Comment by mkaply** [comment]
I was able to find the problem and fix it:

https://github.com/glennjones/microformat-shiv/pull/25

**Comment by glennjones** [comment]
Fixed in latest version v1.4.0. Code changes from #25
